# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appclacks < Formula
  desc ""
  homepage "https://appclacks.com"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/appclacks/cli/releases/download/v1.0.0/appclacks_1.0.0_darwin_arm64.tar.gz"
      sha256 "bce81da0948b1ffd3173e86d7df52bf3cafa6c0f5511f0832308d5ce7918563e"

      def install
        bin.install "appclacks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/appclacks/cli/releases/download/v1.0.0/appclacks_1.0.0_darwin_amd64.tar.gz"
      sha256 "be18d0e85c2b8b57846bfe548153677b2be07726216caba641af0cf5daf73c9c"

      def install
        bin.install "appclacks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/appclacks/cli/releases/download/v1.0.0/appclacks_1.0.0_linux_armv6.tar.gz"
      sha256 "50350faca2a84997864f71b2a0fa6113b8e96858bf9e3c19b9a1a54290c1e689"

      def install
        bin.install "appclacks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/appclacks/cli/releases/download/v1.0.0/appclacks_1.0.0_linux_arm64.tar.gz"
      sha256 "1c7ed3bd85b76fae240d1c50098d7d5784b6ae2899601524808a6d1e120606bd"

      def install
        bin.install "appclacks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/appclacks/cli/releases/download/v1.0.0/appclacks_1.0.0_linux_amd64.tar.gz"
      sha256 "d849bbc38c4d2eb5b300d7208a98c27216e4a854ee673bbb4a71555aec0b0cac"

      def install
        bin.install "appclacks"
      end
    end
  end

  test do
    system "#{bin}/appclacks --help"
  end
end
